name: Docker Image CI/CD

on: 
  push:
    branches: [ "master" ]
    tags: ['*']
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'latest' || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: "docker build . --file Dockerfile --tag revianlabs/r-package-builder:$IMAGE_TAG"
      
    - name: Docker login
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Deploy to Docker Hub
      if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
      run: "docker push revianlabs/r-package-builder:$IMAGE_TAG"
